server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/skillhub
    username: skillhub
    password: skillhub_dev
  data:
    redis:
      host: localhost
      port: 6379
  session:
    store-type: redis
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${OAUTH2_GITHUB_CLIENT_ID:local-placeholder}
            client-secret: ${OAUTH2_GITHUB_CLIENT_SECRET:local-placeholder}
          sourceid:
            client-id: ${OAUTH2_SOURCEID_CLIENT_ID:skillhub}
            client-secret: ${OAUTH2_SOURCEID_CLIENT_SECRET:6N5PrPUkNDhK_yiMJln_OcK_GwM4bK5nSKTCtkhWgMcQT3GTng7-zB6tu18MAtMO}
            authorization-grant-type: authorization_code
            redirect-uri: https://skillhub.ruijie.com.cn/login/oauth2/code/sourceid
            client-name: 锐捷单点登录
        provider:
          sourceid:
            authorization-uri: https://sid.ruijie.com.cn/oauth2.0/authorize
            token-uri: https://sid.ruijie.com.cn/oauth2.0/accessToken
            user-info-uri: https://sid.ruijie.com.cn/oauth2.0/profile
            user-name-attribute: id

skillhub:
  auth:
    mock:
      enabled: true
  bootstrap:
    admin:
<<<<<<< Updated upstream
      enabled: ${BOOTSTRAP_ADMIN_ENABLED:true}
=======
      enabled: true
      user-id: local-admin
      username: admin
      password: Admin@2026
      display-name: Local Admin
      email: admin@skillhub.local
>>>>>>> Stashed changes
  profile:
    moderation:
      machine-review: ${SKILLHUB_PROFILE_MACHINE_REVIEW_ENABLED:true}
      human-review: ${SKILLHUB_PROFILE_HUMAN_REVIEW_ENABLED:true}

logging:
  level:
    com.iflytek.skillhub: INFO
    org.springframework.security: WARN
