apiVersion: v1
kind: Secret
metadata:
  name: skillhub-secret
  namespace: skillhub
type: Opaque
stringData:
  spring-datasource-url: jdbc:postgresql://k8s-bj-pro-nodeports.ruijie.com.cn:32642/skillhub
  spring-datasource-username: change-me
  spring-datasource-password: change-me
  skillhub-storage-s3-endpoint: https://tos-s3-cn-beijing.volces.com
  skillhub-storage-s3-public-endpoint: https://tos-s3-cn-beijing.volces.com
  skillhub-storage-s3-bucket: ruijie-skillhub
  skillhub-storage-s3-access-key: change-me
  skillhub-storage-s3-secret-key: change-me
  skillhub-storage-s3-region: cn-beijing
  bootstrap-admin-enabled: "false"
  bootstrap-admin-user-id: bootstrap-admin
  bootstrap-admin-username: admin
  bootstrap-admin-password: change-me
  bootstrap-admin-display-name: Admin
  bootstrap-admin-email: admin@ruijie.com.cn
  oauth2-github-client-id: ""
  oauth2-github-client-secret: ""
  oauth2-sourceid-client-id: change-me
  oauth2-sourceid-client-secret: change-me
  oauth2-sourceid-redirect-uri: https://skillhub.ruijie.com.cn/login/oauth2/code/sourceid
  oauth2-sourceid-authorization-uri: https://sid.ruijie.com.cn/oauth2.0/authorize
  oauth2-sourceid-token-uri: https://sid.ruijie.com.cn/oauth2.0/accessToken
  oauth2-sourceid-user-info-uri: https://sid.ruijie.com.cn/oauth2.0/profile