apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: skillhub

resources:
  - ../external

patches:
  - path: configmap-s3-patch.yaml
  - path: backend-storage-patch.yaml
  - path: delete-storage-pvc.yaml

labels:
  - pairs:
      app.kubernetes.io/deployment: external-s3