apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: skillhub

resources:
  - ../external-s3

patches:
  - path: configmap-external-patch.yaml
  - path: configmap-sourceid-patch.yaml
  - path: ingress-host-patch.yaml

labels:
  - pairs:
      app.kubernetes.io/deployment: external-s3-sourceid-only